-- Migration: Change transactions.processed_by_user_id from bigint to uuid
-- ⚠️ DO NOT RUN - Another service (Python) uses bigint (Telegram IDs) for this column.
-- The Next.js app maps session.user.id (uuid) -> user_telegram.telegram_id (bigint) when inserting.
--
-- If you must run this, the Python service would need to be updated to use uuid instead of bigint.
